### ISSUE TITLE
module 'flutter_barcode_scanner' not found     @import flutter_barcode_scanner;

### ISSUE THREAD

**Issue by NattawutTanthai** [AmolGangadhare/flutter_barcode_scanner#228]
![Screen Shot 2564-09-10 at 01 49 06](https://user-images.githubusercontent.com/90416683/132745262-3b2bc91a-c20a-4bdb-b5bd-c9aaf9607f0d.png)

**Comment by lohhans** [comment]
Same here, there's any solution?

![Captura de tela de 2021-09-22 16-09-50](https://user-images.githubusercontent.com/30741312/134406612-8f3a2472-0a9b-4b35-b320-2230d08aea17.png)

**Comment by arordakowski** [comment]
Same problem, has anyone found a solution?

**Comment by arordakowski** [comment]
I managed to solve it by opening the Runner.xcodeproj file in Xcode. I navigated to Pods/Development Pods/flutter_barcode_scanner/Pod/flutter_barcode_scanner.podspec. So Xcode recognized the module and built the application without any problems. Hope this helps you too!

![print](https://user-images.githubusercontent.com/42479039/135716529-4dfcf587-823a-44c2-ab44-69c299ef18b7.jpg)

**Comment by liseipi** [comment]
Same problem, has anyone found a solution?

**Comment by darkfrog26** [comment]
Same problem running on MBP M1 Pro laptop. I'm wondering if this is related to the hoops I had to go through to install the pods on the M1. Anyone else having this problem on an M1?

**Comment by pdivita** [comment]
I fixed doing a `flutter clean` and then `pod install`

**Comment by darkfrog26** [comment]
@pdivita, unfortunately, that didn't solve my problem. I'm still getting `Module 'flutter_barcode_scanner' not found`.

**Comment by wallacerodrigon** [comment]
> I managed to solve it by opening the Runner.xcodeproj file in Xcode. I navigated to Pods/Development Pods/flutter_barcode_scanner/Pod/flutter_barcode_scanner.podspec. So Xcode recognized the module and built the application without any problems. Hope this helps you too!
> 
> ![print](https://user-images.githubusercontent.com/42479039/135716529-4dfcf587-823a-44c2-ab44-69c299ef18b7.jpg)

It solved for me. I used MAC OS Monterey e XCode 14.2, guys. It should be one of the problems of yours.
